version: '3.8'
services:
  redis:
    image: "redis:alpine"
#    environment:
#        - ALLOW_EMPTY_PASSWORD=yes
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
#    command: redis-server --loglevel warning --protected-mode no
    volumes:
      - ./cache:/data
  real-time-heatmap:
    build: .
    container_name: real-time-heatmap
#    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    links:
      - "redis:redis"
    volumes:
      - .:/app
    ports:
      - "80:8000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:12
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    container_name: 'database'
    environment:
      POSTGRES_DB: heatmap
      POSTGRES_USER: heatmap
      POSTGRES_PASSWORD: heatmap
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - "5051:8080"

volumes:
  postgres_data:
  cache:
    driver: local